support python 3.10 with ray >= 2.0
PrefectHQ/prefect-ray pull request #105
Opened 2023-11-27 14:57 UTC by j-tr

Closes #104

### Example

Ray supports Python 3.10 from version 2.0.0.

### Screenshots

### Checklist

- [x] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-ray/issues/new/choose) first.
- [x] Includes tests or only affects documentation.
- [x] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [x] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-ray/blob/main/CHANGELOG.md)

2023-11-27 15:28 UTC, j-tr commented
@desertaxle please let me know if you think further changes are necessary in order to support Python 3.10.

2023-11-27 15:31 UTC, desertaxle requested changes
Thanks for the PR @j-tr! We also would want to add tests for Python 3.10 in our CI process. That should be as simple as commenting out this line: https://github.com/PrefectHQ/prefect-ray/blob/340d5d50c4facc3ede0cdd7eab635e6ce34c8ca1/.github/workflows/tests.yml#L16.

2023-11-27 15:31 UTC, desertaxle commented on setup.py
>          "Programming Language :: Python :: 3.7",
`prefect` doesn't support 3.7 so we can drop this line as well.
```suggestion
```

2023-11-27 15:31 UTC, desertaxle commented on CHANGELOG.md
> +- Support Python 3.10
```suggestion
- Support for Python 3.10 - [#105](https://github.com/PrefectHQ/prefect-ray/pull/105)
```

2023-11-29 14:49 UTC, desertaxle commented on CHANGELOG.md
> +Released on November 27th, 2023.
```suggestion
Released on November 29th, 2023.
```

2023-11-29 14:50 UTC, desertaxle approved these changes

2023-11-29 16:02 UTC, merged