Add instructions for remote ray
PrefectHQ/prefect-ray pull request #47
Opened 2022-10-10 21:44 UTC by ahuang11

## Summary

Added instructions for fixing: `PermissionError: [Errno 13] Permission denied: '/Users'`

## Relevant Issue(s)

https://github.com/PrefectHQ/prefect-ray/issues/26

## Checklist
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-ray/blob/main/CHANGELOG.md)

2022-10-10 22:03 UTC, ahuang11 commented
Tests fixed in https://github.com/PrefectHQ/prefect-ray/pull/48

2022-10-11 00:12 UTC, desertaxle requested changes

2022-10-11 00:12 UTC, desertaxle commented on README.md
> +
```suggestion

When using the `RayTaskRunner` with a remote Ray cluster, you may run into issues that are not seen when using a local Ray instance. To resolve these issues, we recommend taking the following steps when working with a remote Ray cluster:

```

2022-10-11 00:12 UTC, desertaxle commented on README.md
> +1. Set `PREFECT_LOCAL_STORAGE_PATH` to a path accessible on both the remote cluster and the machine executing the flow:
```suggestion
1. If your task fail with permission or file not found errors, set `PREFECT_LOCAL_STORAGE_PATH` in your Prefect settings to a path accessible on both the remote cluster and the machine executing the flow:
```

2022-10-11 00:12 UTC, desertaxle commented on README.md
> +2. Ensure `prefect` is installed on the remote cluster, with:
```suggestion
2. If you get an error stating that the module 'prefet' cannot be found, ensure `prefect` is installed on the remote cluster, with:
```

2022-10-11 00:12 UTC, desertaxle commented on README.md
> +3. Pass `address='ray://<head_node_ip_address>:10001'`:
```suggestion
3. If you are seeing timeout or other connection errors, double check the address provided to the `RayTaskRunner`. The address should look similar to: `address='ray://<head_node_ip_address>:10001'`:
```

2022-10-11 00:14 UTC, ahuang11 commented on README.md
> +1. If your task fail with permission or file not found errors, set `PREFECT_LOCAL_STORAGE_PATH` in your Prefect settings to a path accessible on both the remote cluster and the machine executing the
```suggestion
1. If your task fails with permission or file not found errors, set `PREFECT_LOCAL_STORAGE_PATH` in your Prefect settings to a path accessible on both the remote cluster and the machine executing the flow:
```

2022-10-11 00:14 UTC, ahuang11 commented on README.md
> +2. If you get an error stating that the module 'prefet' cannot be found, ensure `prefect` is installed on the remote cluster, with:
```suggestion
2. If you get an error stating that the module 'prefect' cannot be found, ensure `prefect` is installed on the remote cluster, with:
```

2022-10-11 07:02 UTC, tekumara approved these changes

2022-10-11 11:20 UTC, desertaxle approved these changes

2022-10-11 13:32 UTC, merged