Add resources context manager to set CPUs/GPUs for task
PrefectHQ/prefect-ray pull request #54
Opened 2022-10-19 22:32 UTC by ahuang11

This PR allows users to [specify required resources](https://docs.ray.io/en/latest/ray-core/tasks/resources.html#), like CPUs and GPUs, for a task.

To accomplish this, we collect resources kwargs from a user through a context manager (see example below), and then pass this to `ray.remote` internally in `submit` [as suggested by Michael.](https://github.com/PrefectHQ/prefect-ray/issues/44#issuecomment-1266254662).

Closes https://github.com/PrefectHQ/prefect-ray/issues/44

### Example

Use 4 CPUs and 2 GPUs for the `process` task:
```python
from prefect import flow, task
from prefect_ray.task_runners import RayTaskRunner
from prefect_ray.context import resources
@task
def process(x):
    return x + 1
@flow(task_runner=RayTaskRunner())
def my_flow():
    # equivalent to setting @ray.remote(num_cpus=4, num_gpus=2)
    with resources(num_cpus=4, num_gpus=2):
        process.submit(42)
```

### Checklist

- [ ] This pull request references any related issue by including "Closes #<ISSUE_NUMBER>"
	- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/{{ cookiecutter.github_organization }}/{{ cookiecutter.collection_name }}/issues/new/choose) first.
- [ ] This pull request includes tests or only affects documentation.
- [ ] Summarized PR's changes in [CHANGELOG.md](https://github.com/{{ cookiecutter.github_organization }}/{{ cookiecutter.collection_name }}/blob/main/CHANGELOG.md)

2022-10-22 15:28 UTC, desertaxle requested changes

2022-10-22 15:28 UTC, desertaxle commented on prefect_ray/context.py
> +        yield
With the current implementation, the current resources will override any new resources that are provided. I would expect the new resources to take precedence, like in the suggestion. If there's a reason for the current resources to take precedence, let me know, but as a user, I'd expect the most recent value to take precedence if I'm nesting context manager.

A test validating the chosen functionality would also be a good idea.
```suggestion
    with ResourcesContext(current_resources={**current_resources, **new_resources}):
        yield
```

2022-10-24 16:33 UTC, madkinsz commented on README.md
> +    with resources(num_cpus=4, num_gpus=2):
I would name this `remote_options` instead of `resources`. It seems useful to pass other `remote` parameters.

2022-10-25 14:35 UTC, desertaxle approved these changes
LGTM!

2022-10-25 14:42 UTC, madkinsz commented on prefect_ray/context.py
> +    RemoteOptions are always combined with any existing remote_options.
```suggestion
    Context manager to add keyword arguments to Ray `@remote` calls
    for task runs. If contexts are nested, new options are merged with options
    in the outer context. If a key is present in both, the new option will be used.
```

2022-10-25 16:53 UTC, madkinsz approved these changes

2022-10-25 17:23 UTC, merged